CATALOGUE_HOST: catalogue.backend-{{ env }}.daws84s.pro
USER_HOST: user.backend-{{ env }}.daws84s.pro
CART_HOST: cart.backend-{{ env }}.daws84s.pro
SHIPPING_HOST: shipping.backend-{{ env }}.daws84s.pro
PAYMENT_HOST: payment.backend-{{ env }}.daws84s.pro