- name: disable default nginx module
  ansible.builtin.command: dnf module disable nginx -y 

- name: enabling nginx:1.24
  ansible.builtin.command: dnf module enable nginx:1.24 -y 

- name: installing nginx
  ansible.builtin.dnf: 
    name: nginx
    state: present

- name: start and enable nginx
  ansible.builtin.service: 
    name: nginx
    state: started
    enabled: yes

- name: remove the default html content
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent

- name: create html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: download the frontend component code
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /tmp/frontend.zip

- name: extract the downloaded frontend code
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: remove default nginx conf
  ansible.builtin.file:
    path: /etc/nginx/nginx.conf
    state: absent

- name: change the nginx config file to reach backend services
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx


    